[package]
name = "orzklv"
version = "0.0.1"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
telegram = [ "dep:teloxide", "dep:url" ]
string = []

[dependencies]
teloxide = { version = "0.12", optional = true }
url = { version = "2.5.0", optional = true }

[dev-dependencies]
serde = "1.0.196"
serde_json = "1.0.113"